# Generated by Django 4.2.7 on 2024-10-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('current_club', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats_by_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('games', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('season', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.players')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('defeats', models.IntegerField()),
                ('team_goals', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
                ('season', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.players')),
            ],
        ),
    ]
